### Converting bracken output to normalized ASV table

#### let's start with species level

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import os

In [4]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/ID_tables')

In [5]:
os.chdir('/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_filtered')

In [6]:
# Set path variables and create sample list 
SAMPLES='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/ID_tables/all_sampleids.txt'
BRACKENS='/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_filtered'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['072023_Carolina_2023_Baya_053_MCAV_S3', '072023_Carolina_2023_Baya_055_MCAV_S4', '122021_Coralina_2021_Baya_003_MCAV_S27', '122021_Coralina_2021_Baya_005_MCAV_S28', '122021_Coralina_2021_Baya_007_MCAV_S29', '122021_Coralina_2021_Baya_017_MCAV_S30', '122021_Coralina_2021_Baya_023_MCAV_S31', '072023_Carolina_2023_Baya_052_DCYL_S9', '072023_Carolina_2023_Baya_065_DCYL_S1', '072023_Carolina_2023_Baya_066_DCYL_S2', '122021_Coralina_2021_Baya_001_DCYL_S24', '122021_Coralina_2021_Baya_009_DCYL_S25', '122021_Coralina_2021_Baya_010_DCYL_S26', '122021_Coralina_2021_Baya_025_MMEA_S22', '122021_Coralina_2021_Baya_029_MMEA_S23', '122021_Coralina_2021_Baya_031_MMEA_S45', '072023_Carolina_2023_Baya_057_SSID_S7', '072023_Carolina_2023_Baya_059_SSID_S8', '072023_Carolina_2023_Baya_061_SSID_S5', '072023_Carolina_2023_Baya_063_SSID_S6', '122021_Coralina_2021_Baya_019_SSID1_S46', '122021_Coralina_2021_Baya_021_SSID2_S36', '122021_Coralina_2021_Baya_027_PSTR4_S34', '122021_Coralina_2021_Baya_033_PSTR7_S35', '122021_Coralina_2021_Baya_035_PSTR_S32', '122021_Coralina_2021_Baya_037_PSTR_S33', '122021_Coralina_2021_Baya_013_DLAB_S43', '122021_Coralina_2021_Baya_015_DLAB_S44']
072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,122021_Coralina_2021_Baya_009_DCYL_S25,122021_Coralina_2021_Baya_010_DCYL_S26,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
28

In [7]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_filtered/DR_merged_all_bracken_S.txt", sep='\t')

In [8]:
otu_table.set_index("taxonomy_id",inplace=True)

In [9]:
otu_table.head()

,name,taxonomy_lvl,072023_Carolina_2023_Baya_052_DCYL_S9_S_filtered.bracken_num,072023_Carolina_2023_Baya_052_DCYL_S9_S_filtered.bracken_frac,072023_Carolina_2023_Baya_053_MCAV_S3_S_filtered.bracken_num,072023_Carolina_2023_Baya_053_MCAV_S3_S_filtered.bracken_frac,072023_Carolina_2023_Baya_055_MCAV_S4_S_filtered.bracken_num,072023_Carolina_2023_Baya_055_MCAV_S4_S_filtered.bracken_frac,072023_Carolina_2023_Baya_057_SSID_S7_S_filtered.bracken_num,072023_Carolina_2023_Baya_057_SSID_S7_S_filtered.bracken_frac,...,122021_Coralina_2021_Baya_029_MMEA_S23_S_filtered.bracken_num,122021_Coralina_2021_Baya_029_MMEA_S23_S_filtered.bracken_frac,122021_Coralina_2021_Baya_031_MMEA_S45_S_filtered.bracken_num,122021_Coralina_2021_Baya_031_MMEA_S45_S_filtered.bracken_frac,122021_Coralina_2021_Baya_033_PSTR7_S35_S_filtered.bracken_num,122021_Coralina_2021_Baya_033_PSTR7_S35_S_filtered.bracken_frac,122021_Coralina_2021_Baya_035_PSTR_S32_S_filtered.bracken_num,122021_Coralina_2021_Baya_035_PSTR_S32_S_filtered.bracken_frac,122021_Coralina_2021_Baya_037_PSTR_S33_S_filtered.bracken_num,122021_Coralina_2021_Baya_037_PSTR_S33_S_filtered.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
2066072,Bacterioplanoides sp.,S,136309,0.05859,11368,0.04697,13753,0.03105,3551,0.02211,...,169,0.00402,273,0.00257,15317,0.05986,14348,0.06234,12064,0.07134
588596,Rhizophagus irregularis,S,44990,0.01934,4593,0.01898,5736,0.01295,0,0.00000,...,599,0.01424,1103,0.01037,2735,0.01069,0,0.00000,1672,0.00989
562,Escherichia coli,S,14080,0.00605,1566,0.00647,2727,0.00616,1319,0.00821,...,454,0.01079,1125,0.01057,1067,0.00417,911,0.00396,717,0.00424
5722,Trichomonas vaginalis,S,12075,0.00519,1411,0.00583,1804,0.00407,594,0.00370,...,291,0.00692,538,0.00506,1476,0.00577,1313,0.00571,846,0.00500
1280,Staphylococcus aureus,S,9113,0.00392,665,0.00275,890,0.00201,467,0.00291,...,269,0.00639,355,0.00334,942,0.00368,799,0.00347,613,0.00363

Columns: \
Sample num: Number of reads estimated for that species  \
Sample frac: Fraction of total reads in the sample estimated for this species \
[NOTE: Fractions are of total reads classified, unclassified reads not accounted for]

In [11]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")
#output to /bracken_filtered

In [12]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

I think I want to normalize based on number of reads classified for each sample (after filtering out human)

I previously normalized from total reads per sample, but then that includes all the unclassified reads as well as the human classified reads. As long as we are normalizing for differences in reads per sample I think this is better.

In [13]:
# add column for number of classified reads per sample (doing species level right now)

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/slurm_outs/slurm-bracken-filtering-species-52470653.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [ ]:
#This is the pattern in the slurm output I want to pull read #s from
# 242006 reads remaining (213219 reads excluded)

In [14]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [15]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['242006',
 '442864',
 '75078',
 '98696',
 '228444',
 '76951',
 '160448',
 '2326483',
 '125110',
 '224470',
 '64749',
 '48042',
 '35258',
 '95699',
 '42076',
 '106399',
 '160570',
 '255432',
 '473579',
 '912677',
 '364348',
 '793558',
 '670165',
 '255894',
 '230140',
 '169096',
 '107684',
 '871286']

In [16]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'072023_Carolina_2023_Baya_053_MCAV_S3': 242006, '072023_Carolina_2023_Baya_055_MCAV_S4': 442864, '122021_Coralina_2021_Baya_003_MCAV_S27': 75078, '122021_Coralina_2021_Baya_005_MCAV_S28': 98696, '122021_Coralina_2021_Baya_007_MCAV_S29': 228444, '122021_Coralina_2021_Baya_017_MCAV_S30': 76951, '122021_Coralina_2021_Baya_023_MCAV_S31': 160448, '072023_Carolina_2023_Baya_052_DCYL_S9': 2326483, '072023_Carolina_2023_Baya_065_DCYL_S1': 125110, '072023_Carolina_2023_Baya_066_DCYL_S2': 224470, '122021_Coralina_2021_Baya_001_DCYL_S24': 64749, '122021_Coralina_2021_Baya_009_DCYL_S25': 48042, '122021_Coralina_2021_Baya_010_DCYL_S26': 35258, '122021_Coralina_2021_Baya_025_MMEA_S22': 95699, '122021_Coralina_2021_Baya_029_MMEA_S23': 42076, '122021_Coralina_2021_Baya_031_MMEA_S45': 106399, '072023_Carolina_2023_Baya_057_SSID_S7': 160570, '072023_Carolina_2023_Baya_059_SSID_S8': 255432, '072023_Carolina_2023_Baya_061_SSID_S5': 473579, '072023_Carolina_2023_Baya_063_SSID_S6': 912677, '122021_Coralina_2021_Baya_019_SSID1_S46': 364348, '122021_Coralina_2021_Baya_021_SSID2_S36': 793558, '122021_Coralina_2021_Baya_027_PSTR4_S34': 670165, '122021_Coralina_2021_Baya_033_PSTR7_S35': 255894, '122021_Coralina_2021_Baya_035_PSTR_S32': 230140, '122021_Coralina_2021_Baya_037_PSTR_S33': 169096, '122021_Coralina_2021_Baya_013_DLAB_S43': 107684, '122021_Coralina_2021_Baya_015_DLAB_S44': 871286}

In [27]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_S_filtered.bracken_num', '')
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
2066072,136309,11368,13753,3551,4697,4286,3905,345,415,121,...,151,43461,3856,304,10547,169,273,15317,14348,12064
588596,44990,4593,5736,0,1987,2259,1591,1794,1685,559,...,881,8313,3753,895,6083,599,1103,2735,0,1672
562,14080,1566,2727,1319,2549,3361,30110,814,1254,990,...,669,2690,1312,984,4793,454,1125,1067,911,717
5722,12075,1411,1804,594,0,1489,1285,570,646,235,...,7755,5861,944,489,1980,291,538,1476,1313,846
1280,9113,665,890,467,753,1447,1521,277,353,154,...,619,2394,529,416,1506,269,355,942,799,613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2774776,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,53
3378073,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,35
2913501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,23
1967296,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
2170403,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10

In [28]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,...,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
Total_reads,242006,442864,75078,98696,228444,76951,160448,2326483,125110,224470,...,473579,912677,364348,793558,670165,255894,230140,169096,107684,871286

In [29]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
2066072,136309,11368,13753,3551,4697,4286,3905,345,415,121,...,151,43461,3856,304,10547,169,273,15317,14348,12064
588596,44990,4593,5736,0,1987,2259,1591,1794,1685,559,...,881,8313,3753,895,6083,599,1103,2735,0,1672
562,14080,1566,2727,1319,2549,3361,30110,814,1254,990,...,669,2690,1312,984,4793,454,1125,1067,911,717
5722,12075,1411,1804,594,0,1489,1285,570,646,235,...,7755,5861,944,489,1980,291,538,1476,1313,846
1280,9113,665,890,467,753,1447,1521,277,353,154,...,619,2394,529,416,1506,269,355,942,799,613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3378073,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,35
2913501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,23
1967296,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
2170403,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
Total_reads,2326483,242006,442864,160570,255432,473579,912677,125110,224470,64749,...,364348,793558,160448,95699,670165,42076,106399,255894,230140,169096

In [30]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,Sum
Total_reads,2.326483e+06,242006.000000,442864.000000,160570.000000,255432.000000,473579.000000,912677.000000,125110.000000,224470.000000,64749.000000,...,793558.000000,160448.000000,95699.000000,670165.000000,42076.000000,106399.000000,255894.000000,230140.000000,169096.000000,9.657202e+06
2066072,5.859016e+04,46974.041966,31054.680444,22114.965436,18388.455636,9050.232379,4278.622119,2757.573335,1848.799394,1868.754730,...,54767.263388,24032.708416,3176.626715,15737.915290,4016.541496,2565.813588,59856.815713,62344.659772,71344.088565,7.827142e+05
588596,1.933820e+04,18978.868293,12952.057517,0.000000,7778.978358,4770.059483,1743.223506,14339.381344,7506.571034,8633.337967,...,10475.604808,23390.755884,9352.239835,9076.869129,14236.144120,10366.638784,10688.019258,0.000000,9887.874344,3.304785e+05
2057741,5.592132e+02,132.228127,83.547093,205.517843,187.916941,238.608553,473.332844,167.852290,0.000000,11552.301966,...,981.654775,3253.390507,13615.607269,1047.503227,19417.244985,39098.111824,2164.958928,12179.542887,4701.471354,3.047051e+05
5722,5.190238e+03,5830.433956,4073.485314,3699.321168,0.000000,3144.142793,1407.946075,4555.990728,2877.890141,3629.399682,...,7385.723539,5883.526127,5109.771262,2954.496281,6916.056659,5056.438500,5768.013318,5705.222908,5003.075176,2.524185e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910936,4.298334e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.298334e+00
2560434,4.298334e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.298334e+00
3345112,4.298334e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.298334e+00
2714933,4.298334e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.298334e+00
3047030,4.298334e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.298334e+00

In [31]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")

This otu table still has Total_reads row and Sum column. These should be removed and add taxonomy_id label to the first column

### Now let's do phylum level

starting at step 7: reading in the phylum otu table this time

In [32]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_filtered/DR_merged_all_bracken_P.txt", sep='\t')

In [33]:
otu_table.set_index("taxonomy_id",inplace=True)

In [34]:
otu_table.head()

,name,taxonomy_lvl,072023_Carolina_2023_Baya_052_DCYL_S9_P_filtered.bracken_num,072023_Carolina_2023_Baya_052_DCYL_S9_P_filtered.bracken_frac,072023_Carolina_2023_Baya_053_MCAV_S3_P_filtered.bracken_num,072023_Carolina_2023_Baya_053_MCAV_S3_P_filtered.bracken_frac,072023_Carolina_2023_Baya_055_MCAV_S4_P_filtered.bracken_num,072023_Carolina_2023_Baya_055_MCAV_S4_P_filtered.bracken_frac,072023_Carolina_2023_Baya_057_SSID_S7_P_filtered.bracken_num,072023_Carolina_2023_Baya_057_SSID_S7_P_filtered.bracken_frac,...,122021_Coralina_2021_Baya_029_MMEA_S23_P_filtered.bracken_num,122021_Coralina_2021_Baya_029_MMEA_S23_P_filtered.bracken_frac,122021_Coralina_2021_Baya_031_MMEA_S45_P_filtered.bracken_num,122021_Coralina_2021_Baya_031_MMEA_S45_P_filtered.bracken_frac,122021_Coralina_2021_Baya_033_PSTR7_S35_P_filtered.bracken_num,122021_Coralina_2021_Baya_033_PSTR7_S35_P_filtered.bracken_frac,122021_Coralina_2021_Baya_035_PSTR_S32_P_filtered.bracken_num,122021_Coralina_2021_Baya_035_PSTR_S32_P_filtered.bracken_frac,122021_Coralina_2021_Baya_037_PSTR_S33_P_filtered.bracken_num,122021_Coralina_2021_Baya_037_PSTR_S33_P_filtered.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
1224,Pseudomonadota,P,695212,0.29690,76951,0.29199,172424,0.36882,67610,0.35602,...,20559,0.31806,46821,0.35541,83615,0.29658,80795,0.32976,60802,0.31034
1239,Bacillota,P,521491,0.22271,54948,0.20850,81624,0.17459,37307,0.19645,...,14380,0.22247,30598,0.23227,63484,0.22517,56156,0.22920,41364,0.21112
976,Bacteroidota,P,346854,0.14813,39567,0.15014,64334,0.13761,25008,0.13169,...,9863,0.15259,17205,0.13060,44038,0.15620,42386,0.17300,32682,0.16681
4890,Ascomycota,P,138200,0.05902,15533,0.05894,19062,0.04077,8349,0.04396,...,2864,0.04431,4141,0.03143,13740,0.04873,0,0.00000,9307,0.04750
201174,Actinomycetota,P,131194,0.05603,18748,0.07114,28677,0.06134,20034,0.10549,...,3628,0.05613,7104,0.05393,16124,0.05719,14621,0.05967,11668,0.05955

In [35]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species_phylum.csv")
#output to /bracken_filtered

In [36]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species_P.csv")

In [37]:
# add column for number of classified reads per sample (doing species level right now)

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/slurm_outs/slurm-bracken-filtering-phylum-52470654.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [38]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [39]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['263540',
 '467508',
 '96747',
 '127569',
 '252770',
 '100410',
 '181041',
 '2341543',
 '146066',
 '253014',
 '97657',
 '69384',
 '54554',
 '117898',
 '64639',
 '131737',
 '189905',
 '284068',
 '498168',
 '934442',
 '399235',
 '815522',
 '695201',
 '281935',
 '245012',
 '195923',
 '135854',
 '897862']

In [40]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'072023_Carolina_2023_Baya_053_MCAV_S3': 263540, '072023_Carolina_2023_Baya_055_MCAV_S4': 467508, '122021_Coralina_2021_Baya_003_MCAV_S27': 96747, '122021_Coralina_2021_Baya_005_MCAV_S28': 127569, '122021_Coralina_2021_Baya_007_MCAV_S29': 252770, '122021_Coralina_2021_Baya_017_MCAV_S30': 100410, '122021_Coralina_2021_Baya_023_MCAV_S31': 181041, '072023_Carolina_2023_Baya_052_DCYL_S9': 2341543, '072023_Carolina_2023_Baya_065_DCYL_S1': 146066, '072023_Carolina_2023_Baya_066_DCYL_S2': 253014, '122021_Coralina_2021_Baya_001_DCYL_S24': 97657, '122021_Coralina_2021_Baya_009_DCYL_S25': 69384, '122021_Coralina_2021_Baya_010_DCYL_S26': 54554, '122021_Coralina_2021_Baya_025_MMEA_S22': 117898, '122021_Coralina_2021_Baya_029_MMEA_S23': 64639, '122021_Coralina_2021_Baya_031_MMEA_S45': 131737, '072023_Carolina_2023_Baya_057_SSID_S7': 189905, '072023_Carolina_2023_Baya_059_SSID_S8': 284068, '072023_Carolina_2023_Baya_061_SSID_S5': 498168, '072023_Carolina_2023_Baya_063_SSID_S6': 934442, '122021_Coralina_2021_Baya_019_SSID1_S46': 399235, '122021_Coralina_2021_Baya_021_SSID2_S36': 815522, '122021_Coralina_2021_Baya_027_PSTR4_S34': 695201, '122021_Coralina_2021_Baya_033_PSTR7_S35': 281935, '122021_Coralina_2021_Baya_035_PSTR_S32': 245012, '122021_Coralina_2021_Baya_037_PSTR_S33': 195923, '122021_Coralina_2021_Baya_013_DLAB_S43': 135854, '122021_Coralina_2021_Baya_015_DLAB_S44': 897862}

In [41]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_P_filtered.bracken_num', '')
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
1224,695212,76951,172424,67610,89936,205283,444359,42167,99550,37351,...,161428,239118,47542,36784,193268,20559,46821,83615,80795,60802
1239,521491,54948,81624,37307,59384,69983,73722,32814,39596,14601,...,70002,181590,40922,29117,155290,14380,30598,63484,56156,41364
976,346854,39567,64334,25008,40992,47540,70617,22383,35128,10445,...,47722,130071,29265,17389,102693,9863,17205,44038,42386,32682
4890,138200,15533,19062,8349,12895,14086,11750,8302,10165,3568,...,6845,44414,9519,4500,44643,2864,4141,13740,0,9307
201174,131194,18748,28677,20034,25330,64666,213773,9447,19164,13844,...,46676,42835,11774,5076,51747,3628,7104,16124,14621,11668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3123113,25,0,22,0,14,0,12,0,0,0,...,0,12,0,0,15,0,0,0,0,0
2732412,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1293497,0,0,0,0,0,17,31,0,0,0,...,13,54,0,0,0,0,0,25,0,14
1154676,0,0,0,0,0,0,49,0,0,0,...,0,21,0,0,0,0,0,0,0,0
67810,0,0,0,0,0,0,14,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,...,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
Total_reads,263540,467508,96747,127569,252770,100410,181041,2341543,146066,253014,...,498168,934442,399235,815522,695201,281935,245012,195923,135854,897862

In [43]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
1224,695212,76951,172424,67610,89936,205283,444359,42167,99550,37351,...,161428,239118,47542,36784,193268,20559,46821,83615,80795,60802
1239,521491,54948,81624,37307,59384,69983,73722,32814,39596,14601,...,70002,181590,40922,29117,155290,14380,30598,63484,56156,41364
976,346854,39567,64334,25008,40992,47540,70617,22383,35128,10445,...,47722,130071,29265,17389,102693,9863,17205,44038,42386,32682
4890,138200,15533,19062,8349,12895,14086,11750,8302,10165,3568,...,6845,44414,9519,4500,44643,2864,4141,13740,0,9307
201174,131194,18748,28677,20034,25330,64666,213773,9447,19164,13844,...,46676,42835,11774,5076,51747,3628,7104,16124,14621,11668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2732412,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1293497,0,0,0,0,0,17,31,0,0,0,...,13,54,0,0,0,0,0,25,0,14
1154676,0,0,0,0,0,0,49,0,0,0,...,0,21,0,0,0,0,0,0,0,0
67810,0,0,0,0,0,0,14,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Total_reads,2341543,263540,467508,189905,284068,498168,934442,146066,253014,97657,...,399235,815522,181041,117898,695201,64639,131737,281935,245012,195923

In [44]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,Sum
Total_reads,2.341543e+06,263540.000000,467508.000000,189905.000000,284068.000000,498168.000000,934442.000000,146066.000000,253014.000000,97657.000000,...,815522.000000,181041.000000,117898.000000,695201.000000,64639.000000,131737.000000,281935.000000,245012.000000,195923.000000,1.033920e+07
1224,2.969034e+05,291989.830766,368815.079100,356020.115321,316600.250644,412075.845899,475534.062039,288684.567250,393456.488574,382471.302620,...,293208.521659,262603.498655,311998.507184,278003.052355,318058.757097,355412.678291,296575.451789,329759.358725,310336.203509,9.256583e+06
1239,2.227125e+05,208499.658496,174593.803742,196450.857007,209048.537674,140480.721363,78894.142173,224651.869703,156497.268926,149513.091739,...,222667.199659,226037.195994,246967.717858,223374.247160,222466.312907,232265.802318,225172.468831,229196.937293,211123.757803,5.580043e+06
976,1.481305e+05,150136.601654,137610.479393,131686.896080,144303.476632,95429.654253,75571.303516,153238.946777,138838.167058,106955.978578,...,159494.164474,161648.466369,147491.899778,147716.991201,152585.900153,130601.121932,156199.123912,172995.608378,166810.430628,3.960489e+06
201174,5.602887e+04,71139.106018,61340.126800,105494.852690,89168.790571,129807.615102,228770.753027,64676.242247,75742.844269,141761.471272,...,52524.640660,65034.992074,43054.165465,74434.587982,56127.105927,53925.624540,57190.487169,59674.628181,59554.008463,2.224432e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138240,5.509188e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.509188e+01
2732448,3.160309e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.160309e+01
67810,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,14.982203,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.498220e+01
3412625,1.153086e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.153086e+01
2732412,1.024965e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.024965e+01

In [46]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species_P.csv")