### Converting bracken output to normalized ASV table

#### let's start with species level

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import os

In [4]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/ID_tables')

In [5]:
os.chdir('/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_ready')

In [16]:
# Set path variables and create sample list 
SAMPLES='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/ID_tables/all_sampleids.txt'
BRACKENS='/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_ready/species'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['072023_Carolina_2023_Baya_053_MCAV_S3', '072023_Carolina_2023_Baya_055_MCAV_S4', '122021_Coralina_2021_Baya_003_MCAV_S27', '122021_Coralina_2021_Baya_005_MCAV_S28', '122021_Coralina_2021_Baya_007_MCAV_S29', '122021_Coralina_2021_Baya_017_MCAV_S30', '122021_Coralina_2021_Baya_023_MCAV_S31', '072023_Carolina_2023_Baya_052_DCYL_S9', '072023_Carolina_2023_Baya_065_DCYL_S1', '072023_Carolina_2023_Baya_066_DCYL_S2', '122021_Coralina_2021_Baya_001_DCYL_S24', '122021_Coralina_2021_Baya_009_DCYL_S25', '122021_Coralina_2021_Baya_010_DCYL_S26', '122021_Coralina_2021_Baya_025_MMEA_S22', '122021_Coralina_2021_Baya_029_MMEA_S23', '122021_Coralina_2021_Baya_031_MMEA_S45', '072023_Carolina_2023_Baya_057_SSID_S7', '072023_Carolina_2023_Baya_059_SSID_S8', '072023_Carolina_2023_Baya_061_SSID_S5', '072023_Carolina_2023_Baya_063_SSID_S6', '122021_Coralina_2021_Baya_019_SSID1_S46', '122021_Coralina_2021_Baya_021_SSID2_S36', '122021_Coralina_2021_Baya_027_PSTR4_S34', '122021_Coralina_2021_Baya_033_PSTR7_S35', '122021_Coralina_2021_Baya_035_PSTR_S32', '122021_Coralina_2021_Baya_037_PSTR_S33', '122021_Coralina_2021_Baya_013_DLAB_S43', '122021_Coralina_2021_Baya_015_DLAB_S44']
072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,122021_Coralina_2021_Baya_009_DCYL_S25,122021_Coralina_2021_Baya_010_DCYL_S26,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
28

In [7]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_ready/all_merged_bracken_S.txt", sep='\t')

In [8]:
otu_table.set_index("taxonomy_id",inplace=True)

In [9]:
otu_table.head()

,name,taxonomy_lvl,072023_Carolina_2023_Baya_052_DCYL_S9_S_filt.bracken_num,072023_Carolina_2023_Baya_052_DCYL_S9_S_filt.bracken_frac,072023_Carolina_2023_Baya_053_MCAV_S3_S_filt.bracken_num,072023_Carolina_2023_Baya_053_MCAV_S3_S_filt.bracken_frac,072023_Carolina_2023_Baya_055_MCAV_S4_S_filt.bracken_num,072023_Carolina_2023_Baya_055_MCAV_S4_S_filt.bracken_frac,072023_Carolina_2023_Baya_057_SSID_S7_S_filt.bracken_num,072023_Carolina_2023_Baya_057_SSID_S7_S_filt.bracken_frac,...,122021_Coralina_2021_Baya_029_MMEA_S23_S_filt.bracken_num,122021_Coralina_2021_Baya_029_MMEA_S23_S_filt.bracken_frac,122021_Coralina_2021_Baya_031_MMEA_S45_S_filt.bracken_num,122021_Coralina_2021_Baya_031_MMEA_S45_S_filt.bracken_frac,122021_Coralina_2021_Baya_033_PSTR7_S35_S_filt.bracken_num,122021_Coralina_2021_Baya_033_PSTR7_S35_S_filt.bracken_frac,122021_Coralina_2021_Baya_035_PSTR_S32_S_filt.bracken_num,122021_Coralina_2021_Baya_035_PSTR_S32_S_filt.bracken_frac,122021_Coralina_2021_Baya_037_PSTR_S33_S_filt.bracken_num,122021_Coralina_2021_Baya_037_PSTR_S33_S_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
588596,Rhizophagus irregularis,S,19466,0.01689,1142,0.00959,1539,0.00558,716,0.00674,...,345,0.01615,664,0.01067,1484,0.01151,1219,0.00993,849,0.01016
311410,Roseibium album,S,8042,0.00698,0,0.00000,23,0.00008,0,0.00000,...,0,0.00000,0,0.00000,25,0.00019,10,0.00008,16,0.00019
5722,Trichomonas vaginalis,S,6083,0.00528,575,0.00483,731,0.00265,316,0.00298,...,124,0.00581,182,0.00292,606,0.00470,548,0.00446,341,0.00408
562,Escherichia coli,S,5839,0.00506,742,0.00623,1898,0.00688,951,0.00895,...,303,0.01419,1066,0.01712,690,0.00535,585,0.00477,453,0.00542
106654,Acinetobacter nosocomialis,S,5750,0.00499,0,0.00000,0,0.00000,0,0.00000,...,0,0.00000,33,0.00053,48,0.00037,47,0.00038,24,0.00029

Columns: \
Sample num: Number of reads estimated for that species  \
Sample frac: Fraction of total reads in the sample estimated for this species \
[NOTE: Fractions are of total reads classified, unclassified reads not accounted for]

In [10]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")
#output to /bracken_ready

In [11]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

I think I want to normalize based on number of reads classified for each sample (after filtering out human)

I previously normalized from total reads per sample, but then that includes all the unclassified reads as well as the human classified reads. As long as we are normalizing for differences in reads per sample I think this is better.

In [12]:
# add column for number of classified reads per sample (doing species level right now)

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/slurm_outs/slurm-bracken-filtering-S-60569483.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [ ]:
#This is the pattern in the slurm output I want to pull read #s from
# 242006 reads remaining (213219 reads excluded)

In [13]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [14]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['119041',
 '275961',
 '31441',
 '46677',
 '115215',
 '31184',
 '75058',
 '1152824',
 '68316',
 '157717',
 '43321',
 '25337',
 '20030',
 '53475',
 '21357',
 '62249',
 '106217',
 '163770',
 '367338',
 '804040',
 '259683',
 '385846',
 '411063',
 '128977',
 '122740',
 '83531',
 '64881',
 '523898']

In [15]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'072023_Carolina_2023_Baya_053_MCAV_S3': 119041, '072023_Carolina_2023_Baya_055_MCAV_S4': 275961, '122021_Coralina_2021_Baya_003_MCAV_S27': 31441, '122021_Coralina_2021_Baya_005_MCAV_S28': 46677, '122021_Coralina_2021_Baya_007_MCAV_S29': 115215, '122021_Coralina_2021_Baya_017_MCAV_S30': 31184, '122021_Coralina_2021_Baya_023_MCAV_S31': 75058, '072023_Carolina_2023_Baya_052_DCYL_S9': 1152824, '072023_Carolina_2023_Baya_065_DCYL_S1': 68316, '072023_Carolina_2023_Baya_066_DCYL_S2': 157717, '122021_Coralina_2021_Baya_001_DCYL_S24': 43321, '122021_Coralina_2021_Baya_009_DCYL_S25': 25337, '122021_Coralina_2021_Baya_010_DCYL_S26': 20030, '122021_Coralina_2021_Baya_025_MMEA_S22': 53475, '122021_Coralina_2021_Baya_029_MMEA_S23': 21357, '122021_Coralina_2021_Baya_031_MMEA_S45': 62249, '072023_Carolina_2023_Baya_057_SSID_S7': 106217, '072023_Carolina_2023_Baya_059_SSID_S8': 163770, '072023_Carolina_2023_Baya_061_SSID_S5': 367338, '072023_Carolina_2023_Baya_063_SSID_S6': 804040, '122021_Coralina_2021_Baya_019_SSID1_S46': 259683, '122021_Coralina_2021_Baya_021_SSID2_S36': 385846, '122021_Coralina_2021_Baya_027_PSTR4_S34': 411063, '122021_Coralina_2021_Baya_033_PSTR7_S35': 128977, '122021_Coralina_2021_Baya_035_PSTR_S32': 122740, '122021_Coralina_2021_Baya_037_PSTR_S33': 83531, '122021_Coralina_2021_Baya_013_DLAB_S43': 64881, '122021_Coralina_2021_Baya_015_DLAB_S44': 523898}

In [17]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_S_filt.bracken_num', '')
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
588596,19466,1142,1539,716,1058,1321,910,747,792,262,...,289,3792,864,518,3845,345,664,1484,1219,849
311410,8042,0,23,0,10,53,201,0,17,15,...,19,16,0,0,28,0,0,25,10,16
5722,6083,575,731,316,538,750,595,270,312,123,...,3160,1854,362,224,1135,124,182,606,548,341
562,5839,742,1898,951,1954,2808,5742,311,696,878,...,552,1697,796,730,3338,303,1066,690,585,453
106654,5750,0,0,0,14,36,65,0,45,0,...,0,108,24,33,129,0,33,48,47,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3060540,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
1340801,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
2749077,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,53
3378073,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,35
2170403,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10

In [18]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,...,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
Total_reads,119041,275961,31441,46677,115215,31184,75058,1152824,68316,157717,...,367338,804040,259683,385846,411063,128977,122740,83531,64881,523898

In [19]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
588596,19466,1142,1539,716,1058,1321,910,747,792,262,...,289,3792,864,518,3845,345,664,1484,1219,849
311410,8042,0,23,0,10,53,201,0,17,15,...,19,16,0,0,28,0,0,25,10,16
5722,6083,575,731,316,538,750,595,270,312,123,...,3160,1854,362,224,1135,124,182,606,548,341
562,5839,742,1898,951,1954,2808,5742,311,696,878,...,552,1697,796,730,3338,303,1066,690,585,453
106654,5750,0,0,0,14,36,65,0,45,0,...,0,108,24,33,129,0,33,48,47,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340801,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
2749077,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,53
3378073,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,35
2170403,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10
Total_reads,1152824,119041,275961,106217,163770,367338,804040,68316,157717,43321,...,259683,385846,75058,53475,411063,21357,62249,128977,122740,83531

In [20]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,Sum
Total_reads,1.152824e+06,119041.000000,275961.000000,106217.000000,163770.000000,367338.000000,804040.000000,68316.000000,157717.000000,43321.000000,...,385846.000000,75058.000000,53475.000000,411063.000000,21357.000000,62249.000000,128977.000000,122740.000000,83531.000000,5.721187e+06
2057741,1.127666e+03,319.217749,148.571718,329.514108,305.306222,313.063173,532.311825,307.395047,0.000000,17705.039127,...,2016.348491,6941.298729,24385.226741,1471.793861,38675.843986,66764.124725,4442.652566,22942.805931,9828.686356,5.144996e+05
5722,5.276608e+03,4830.268563,2648.925029,2975.041660,3285.094950,2041.716348,740.012935,3952.222027,1978.226824,2839.269638,...,4805.025839,4822.936929,4188.873305,2761.133938,5806.058903,2923.741747,4698.512138,4464.722177,4082.316745,3.026703e+05
562,5.064954e+03,6233.146563,6877.783455,8953.369046,11931.367161,7644.186009,7141.435749,4552.374261,4412.967530,20267.306849,...,4398.127750,10605.132031,13651.238897,8120.409767,14187.385869,17124.773089,5349.791048,4766.172397,5423.136321,2.629771e+05
588596,1.688549e+04,9593.333389,5576.874993,6740.917179,6460.279660,3596.143062,1131.784488,10934.480942,5021.652707,6047.875164,...,9827.755115,11511.098084,9686.769518,9353.797350,16153.954207,10666.838021,11505.927413,9931.562653,10163.891250,2.586352e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3127115,8.674351e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.674351e+00
2560434,8.674351e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.674351e+00
2968831,8.674351e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.674351e+00
2051,8.674351e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.674351e+00
3345112,8.674351e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.674351e+00

In [21]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")

This otu table still has Total_reads row and Sum column. These should be removed and add taxonomy_id label to the first column

### Now let's do Kingdom level

starting at step 7: reading in the kingdom otu table this time

In [22]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_ready/all_merged_bracken_K.txt", sep='\t')

In [23]:
otu_table.set_index("taxonomy_id",inplace=True)

In [24]:
otu_table.head()

,name,taxonomy_lvl,072023_Carolina_2023_Baya_052_DCYL_S9_K_filt.bracken_num,072023_Carolina_2023_Baya_052_DCYL_S9_K_filt.bracken_frac,072023_Carolina_2023_Baya_053_MCAV_S3_K_filt.bracken_num,072023_Carolina_2023_Baya_053_MCAV_S3_K_filt.bracken_frac,072023_Carolina_2023_Baya_055_MCAV_S4_K_filt.bracken_num,072023_Carolina_2023_Baya_055_MCAV_S4_K_filt.bracken_frac,072023_Carolina_2023_Baya_057_SSID_S7_K_filt.bracken_num,072023_Carolina_2023_Baya_057_SSID_S7_K_filt.bracken_frac,...,122021_Coralina_2021_Baya_029_MMEA_S23_K_filt.bracken_num,122021_Coralina_2021_Baya_029_MMEA_S23_K_filt.bracken_frac,122021_Coralina_2021_Baya_031_MMEA_S45_K_filt.bracken_num,122021_Coralina_2021_Baya_031_MMEA_S45_K_filt.bracken_frac,122021_Coralina_2021_Baya_033_PSTR7_S35_K_filt.bracken_num,122021_Coralina_2021_Baya_033_PSTR7_S35_K_filt.bracken_frac,122021_Coralina_2021_Baya_035_PSTR_S32_K_filt.bracken_num,122021_Coralina_2021_Baya_035_PSTR_S32_K_filt.bracken_frac,122021_Coralina_2021_Baya_037_PSTR_S33_K_filt.bracken_num,122021_Coralina_2021_Baya_037_PSTR_S33_K_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3379134,Pseudomonadati,K,580304,0.49562,70881,0.50194,198189,0.65373,76820,0.56019,...,23646,0.57002,51278,0.59860,77956,0.50126,79320,0.53365,58084,0.52863
1783272,Bacillati,K,401741,0.34312,47538,0.33664,75913,0.25040,45852,0.33437,...,12697,0.30608,25016,0.29203,54680,0.35159,48854,0.32868,36972,0.33649
4751,Fungi,K,134770,0.11510,16585,0.11745,20395,0.06727,9442,0.06885,...,3592,0.08659,6248,0.07294,16132,0.10373,14524,0.09771,10482,0.09540
3366610,Methanobacteriati,K,17229,0.01471,1943,0.01376,2704,0.00892,1876,0.01368,...,457,0.01102,890,0.01039,2352,0.01512,2080,0.01399,1604,0.01460
3384189,Fusobacteriati,K,12800,0.01093,1262,0.00894,1828,0.00603,740,0.00540,...,336,0.00810,770,0.00899,1330,0.00855,1208,0.00813,834,0.00759

In [25]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species_kingdom.csv")
#output to /bracken_ready

In [26]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_kingdom.csv")

In [27]:
# add column for number of classified reads per sample (doing species level right now)

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/slurm_outs/slurm-bracken-filtering-K-60569484.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [28]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [29]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['141213',
 '303168',
 '49947',
 '73825',
 '139336',
 '52193',
 '94263',
 '1170856',
 '88588',
 '187011',
 '74574',
 '43338',
 '36381',
 '74346',
 '41483',
 '85663',
 '137131',
 '192320',
 '394542',
 '827632',
 '294164',
 '409942',
 '440200',
 '155520',
 '148638',
 '109877',
 '91820',
 '551823']

In [30]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'072023_Carolina_2023_Baya_053_MCAV_S3': 141213, '072023_Carolina_2023_Baya_055_MCAV_S4': 303168, '122021_Coralina_2021_Baya_003_MCAV_S27': 49947, '122021_Coralina_2021_Baya_005_MCAV_S28': 73825, '122021_Coralina_2021_Baya_007_MCAV_S29': 139336, '122021_Coralina_2021_Baya_017_MCAV_S30': 52193, '122021_Coralina_2021_Baya_023_MCAV_S31': 94263, '072023_Carolina_2023_Baya_052_DCYL_S9': 1170856, '072023_Carolina_2023_Baya_065_DCYL_S1': 88588, '072023_Carolina_2023_Baya_066_DCYL_S2': 187011, '122021_Coralina_2021_Baya_001_DCYL_S24': 74574, '122021_Coralina_2021_Baya_009_DCYL_S25': 43338, '122021_Coralina_2021_Baya_010_DCYL_S26': 36381, '122021_Coralina_2021_Baya_025_MMEA_S22': 74346, '122021_Coralina_2021_Baya_029_MMEA_S23': 41483, '122021_Coralina_2021_Baya_031_MMEA_S45': 85663, '072023_Carolina_2023_Baya_057_SSID_S7': 137131, '072023_Carolina_2023_Baya_059_SSID_S8': 192320, '072023_Carolina_2023_Baya_061_SSID_S5': 394542, '072023_Carolina_2023_Baya_063_SSID_S6': 827632, '122021_Coralina_2021_Baya_019_SSID1_S46': 294164, '122021_Coralina_2021_Baya_021_SSID2_S36': 409942, '122021_Coralina_2021_Baya_027_PSTR4_S34': 440200, '122021_Coralina_2021_Baya_033_PSTR7_S35': 155520, '122021_Coralina_2021_Baya_035_PSTR_S32': 148638, '122021_Coralina_2021_Baya_037_PSTR_S33': 109877, '122021_Coralina_2021_Baya_013_DLAB_S43': 91820, '122021_Coralina_2021_Baya_015_DLAB_S44': 551823}

In [31]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_K_filt.bracken_num', '')
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3379134,580304,70881,198189,76820,104567,228686,512160,47851,116318,43897,...,181218,203924,45794,41490,220647,23646,51278,77956,79320,58084
1783272,401741,47538,75913,45852,65581,139454,287488,27315,55150,24735,...,94221,145265,33608,23570,156360,12697,25016,54680,48854,36972
4751,134770,16585,20395,9442,14973,17422,15064,9082,10555,3878,...,12864,42506,10128,6092,44295,3592,6248,16132,14524,10482
3366610,17229,1943,2704,1876,2768,3856,6681,1069,1587,724,...,2051,6118,1280,868,7738,457,890,2352,2080,1604
3384189,12800,1262,1828,740,1159,1286,1523,733,829,301,...,594,4159,1588,634,2768,336,770,1330,1208,834
2731360,6339,536,751,541,823,933,1049,536,507,224,...,896,1745,378,334,1837,152,208,835,554,422
3384194,5714,735,1080,492,750,1239,2262,519,715,306,...,1745,1769,391,264,1958,175,301,670,593,431
1783275,5290,788,1096,904,951,909,850,849,809,300,...,181,2491,572,704,2411,244,672,943,925,650
2732005,3104,507,656,238,386,476,335,543,453,145,...,155,962,277,322,1586,124,179,355,347,212
2732397,1350,98,156,0,0,0,0,0,0,0,...,0,291,110,0,28,0,0,0,0,0
2732396,1076,145,150,119,181,122,97,32,46,27,...,34,430,97,36,345,43,50,187,172,135
1935183,662,69,86,68,110,105,79,49,42,13,...,187,157,28,20,114,0,31,39,28,28
2732092,168,40,34,17,35,32,16,10,0,13,...,0,88,0,12,48,17,20,41,23,23
1783276,164,61,86,22,36,22,28,0,0,11,...,18,37,12,0,34,0,0,0,10,0
2732093,70,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2840023,38,25,44,0,0,0,0,0,0,0,...,0,0,0,0,31,0,0,0,0,0
2732091,20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3412606,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,...,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
Total_reads,141213,303168,49947,73825,139336,52193,94263,1170856,88588,187011,...,394542,827632,294164,409942,440200,155520,148638,109877,91820,551823

In [33]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
3379134,580304,70881,198189,76820,104567,228686,512160,47851,116318,43897,...,181218,203924,45794,41490,220647,23646,51278,77956,79320,58084
1783272,401741,47538,75913,45852,65581,139454,287488,27315,55150,24735,...,94221,145265,33608,23570,156360,12697,25016,54680,48854,36972
4751,134770,16585,20395,9442,14973,17422,15064,9082,10555,3878,...,12864,42506,10128,6092,44295,3592,6248,16132,14524,10482
3366610,17229,1943,2704,1876,2768,3856,6681,1069,1587,724,...,2051,6118,1280,868,7738,457,890,2352,2080,1604
3384189,12800,1262,1828,740,1159,1286,1523,733,829,301,...,594,4159,1588,634,2768,336,770,1330,1208,834
2731360,6339,536,751,541,823,933,1049,536,507,224,...,896,1745,378,334,1837,152,208,835,554,422
3384194,5714,735,1080,492,750,1239,2262,519,715,306,...,1745,1769,391,264,1958,175,301,670,593,431
1783275,5290,788,1096,904,951,909,850,849,809,300,...,181,2491,572,704,2411,244,672,943,925,650
2732005,3104,507,656,238,386,476,335,543,453,145,...,155,962,277,322,1586,124,179,355,347,212
2732397,1350,98,156,0,0,0,0,0,0,0,...,0,291,110,0,28,0,0,0,0,0
2732396,1076,145,150,119,181,122,97,32,46,27,...,34,430,97,36,345,43,50,187,172,135
1935183,662,69,86,68,110,105,79,49,42,13,...,187,157,28,20,114,0,31,39,28,28
2732092,168,40,34,17,35,32,16,10,0,13,...,0,88,0,12,48,17,20,41,23,23
1783276,164,61,86,22,36,22,28,0,0,11,...,18,37,12,0,34,0,0,0,10,0
2732093,70,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2840023,38,25,44,0,0,0,0,0,0,0,...,0,0,0,0,31,0,0,0,0,0
2732091,20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3412606,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Total_reads,1170856,141213,303168,137131,192320,394542,827632,88588,187011,74574,...,294164,409942,94263,74346,440200,41483,85663,155520,148638,109877

In [34]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,Sum
3379134,4.956237e+05,501943.872023,653726.646612,560194.266796,543713.602329,579623.969058,618825.758308,540152.165079,621984.803033,588636.790302,...,497445.980163,485810.975674,558066.338471,501242.616992,570016.633320,598601.496562,501260.288066,533645.501150,528627.465257,1.534309e+07
1783272,3.431173e+05,336640.394298,250399.118640,334366.408762,340999.376040,353457.933503,347362.112630,308337.472344,294902.438894,331683.964921,...,354355.006318,356534.377221,317031.178544,355202.180827,306077.188246,292028.063458,351594.650206,328677.727095,336485.342701,9.149334e+06
Total_reads,1.170856e+06,141213.000000,303168.000000,137131.000000,192320.000000,394542.000000,827632.000000,88588.000000,187011.000000,74574.000000,...,409942.000000,94263.000000,74346.000000,440200.000000,41483.000000,85663.000000,155520.000000,148638.000000,109877.000000,6.409794e+06
4751,1.151038e+05,117446.694001,67272.931180,68853.869657,77854.617304,44157.529490,18201.326193,102519.528604,56440.530236,52002.038244,...,103687.838767,107444.066070,81941.193877,100624.716038,86589.687342,72936.973956,103729.423868,97713.908960,95397.580931,2.463905e+06
3366610,1.471488e+04,13759.356433,8919.147140,13680.349447,14392.678869,9773.357463,8072.428326,12067.097124,8486.131832,9708.477485,...,14924.062428,13579.028887,11675.140559,17578.373467,11016.561001,10389.549747,15123.456790,13993.729733,14598.141558,3.424558e+05
3384189,1.093217e+04,8936.854256,6029.660122,5396.299888,6026.414309,3259.475544,1840.189843,8274.258365,4432.894322,4036.259286,...,10145.337633,16846.482713,8527.694832,6288.050886,8099.703493,8988.711579,8551.954733,8127.127652,7590.305523,2.168060e+05
1783275,4.518062e+03,5580.222784,3615.157273,6592.236620,4944.883527,2303.937223,1027.026505,9583.690793,4325.948741,4022.849787,...,6076.469354,6068.128534,9469.238426,5477.055884,5881.927537,7844.693742,6063.528807,6223.173078,5915.705744,1.471097e+05
3384194,4.880190e+03,5204.903231,3562.381254,3587.810196,3899.750416,3140.350077,2733.098769,5858.581298,3823.304511,4103.306783,...,4315.244596,4147.968980,3550.964410,4447.978192,4218.595569,3513.769072,4308.127572,3989.558525,3922.567962,1.169489e+05
2731360,5.413988e+03,3795.684533,2477.174372,3945.132756,4279.326123,2364.767249,1267.471533,6050.480878,2711.070472,3003.727841,...,4256.699728,4010.056968,4492.508003,4173.103135,3664.151580,2428.119491,5369.084362,3727.176092,3840.658191,1.052281e+05
2732005,2.651052e+03,3590.321004,2163.816762,1735.566721,2007.071547,1206.462176,404.769269,6129.498352,2422.317404,1944.377397,...,2346.673432,2938.586720,4331.100530,3602.907769,2989.176289,2089.583601,2282.664609,2334.530874,1929.430181,7.205754e+04
2732396,9.189858e+02,1026.817644,494.775174,867.783360,941.139767,309.219297,117.201848,361.222739,245.974836,362.056481,...,1048.928873,1029.035783,484.222419,783.734666,1036.569197,583.682570,1202.417695,1157.173805,1228.646578,1.950599e+04
1935183,5.653983e+02,488.623569,283.671100,495.876206,571.963394,266.131362,95.453052,553.122319,224.585720,174.323491,...,382.981007,297.041257,269.012455,258.973194,0.000000,361.883193,250.771605,188.377131,254.830401,9.026239e+03
2732397,1.153003e+03,693.987098,514.566181,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,709.856516,1166.947795,0.000000,63.607451,0.000000,0.000000,0.000000,0.000000,0.000000,6.425356e+03
2732092,1.434848e+02,283.260040,112.149039,123.969051,181.988353,81.106701,19.332264,112.882106,0.000000,174.323491,...,214.664514,0.000000,161.407473,109.041345,409.806427,233.473028,263.631687,154.738358,209.324972,4.534901e+03
1783276,1.400685e+02,431.971561,283.671100,160.430537,187.188020,55.760857,33.831461,0.000000,0.000000,147.504492,...,90.256670,127.303396,0.000000,77.237619,0.000000,0.000000,0.000000,67.277547,0.000000,2.793331e+03
2840023,3.245489e+01,177.037525,145.134051,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,70.422535,0.000000,0.000000,0.000000,0.000000,0.000000,6.880721e+02
2732093,5.978532e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.978532e+01
2732091,1.708152e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.708152e+01
3412606,1.451929e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.451929e+01

In [35]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_kingdom.csv")

## Now family level

In [7]:
otu_table_f=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_ready/all_merged_bracken_F.txt", sep='\t')

In [8]:
otu_table_f.set_index("taxonomy_id",inplace=True)
otu_table_f.head()

,name,taxonomy_lvl,072023_Carolina_2023_Baya_052_DCYL_S9_F_filt.bracken_num,072023_Carolina_2023_Baya_052_DCYL_S9_F_filt.bracken_frac,072023_Carolina_2023_Baya_053_MCAV_S3_F_filt.bracken_num,072023_Carolina_2023_Baya_053_MCAV_S3_F_filt.bracken_frac,072023_Carolina_2023_Baya_055_MCAV_S4_F_filt.bracken_num,072023_Carolina_2023_Baya_055_MCAV_S4_F_filt.bracken_frac,072023_Carolina_2023_Baya_057_SSID_S7_F_filt.bracken_num,072023_Carolina_2023_Baya_057_SSID_S7_F_filt.bracken_frac,...,122021_Coralina_2021_Baya_029_MMEA_S23_F_filt.bracken_num,122021_Coralina_2021_Baya_029_MMEA_S23_F_filt.bracken_frac,122021_Coralina_2021_Baya_031_MMEA_S45_F_filt.bracken_num,122021_Coralina_2021_Baya_031_MMEA_S45_F_filt.bracken_frac,122021_Coralina_2021_Baya_033_PSTR7_S35_F_filt.bracken_num,122021_Coralina_2021_Baya_033_PSTR7_S35_F_filt.bracken_frac,122021_Coralina_2021_Baya_035_PSTR_S32_F_filt.bracken_num,122021_Coralina_2021_Baya_035_PSTR_S32_F_filt.bracken_frac,122021_Coralina_2021_Baya_037_PSTR_S33_F_filt.bracken_num,122021_Coralina_2021_Baya_037_PSTR_S33_F_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
49546,Flavobacteriaceae,F,85828,0.07342,10467,0.07488,21432,0.07098,7583,0.05593,...,2926,0.07304,4295,0.05099,11171,0.07244,9872,0.06700,7463,0.06891
186817,Bacillaceae,F,70727,0.06050,8020,0.05737,12471,0.04130,6823,0.05032,...,2471,0.06168,4600,0.05461,10579,0.06860,9267,0.06289,6788,0.06268
31979,Clostridiaceae,F,36511,0.03123,3112,0.02226,5494,0.01819,2037,0.01502,...,971,0.02424,2074,0.02462,4311,0.02796,3816,0.02590,2624,0.02423
543,Enterobacteriaceae,F,28875,0.02470,3537,0.02530,8342,0.02763,4084,0.03012,...,1634,0.04079,2407,0.02857,4370,0.02834,3627,0.02461,3425,0.03163
468,Moraxellaceae,F,26901,0.02301,1908,0.01365,3224,0.01068,1657,0.01222,...,767,0.01915,1501,0.01782,2786,0.01807,2616,0.01775,1683,0.01554

In [9]:
# Make taxa otu id table 
otu_id_f=otu_table_f.iloc[:, 0:2]
otu_id_f
# export otu id 
otu_id_f.to_csv("otu_id_family.csv")
#output to /bracken_ready

In [11]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table_f.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_family=otu_table_f.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_family.to_csv("otu_table_family.csv")

In [12]:
# add column for number of classified reads per sample (doing species level right now)

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/slurm_outs/slurm-bracken-filtering-F-62763098.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [13]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [14]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['139792',
 '301955',
 '48554',
 '72316',
 '137799',
 '50856',
 '92844',
 '1169015',
 '86830',
 '185749',
 '73062',
 '41985',
 '34868',
 '72876',
 '40060',
 '84236',
 '135591',
 '191087',
 '393463',
 '826442',
 '292470',
 '408795',
 '438862',
 '154206',
 '147351',
 '108298',
 '90467',
 '549905']

In [17]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'072023_Carolina_2023_Baya_053_MCAV_S3': 139792, '072023_Carolina_2023_Baya_055_MCAV_S4': 301955, '122021_Coralina_2021_Baya_003_MCAV_S27': 48554, '122021_Coralina_2021_Baya_005_MCAV_S28': 72316, '122021_Coralina_2021_Baya_007_MCAV_S29': 137799, '122021_Coralina_2021_Baya_017_MCAV_S30': 50856, '122021_Coralina_2021_Baya_023_MCAV_S31': 92844, '072023_Carolina_2023_Baya_052_DCYL_S9': 1169015, '072023_Carolina_2023_Baya_065_DCYL_S1': 86830, '072023_Carolina_2023_Baya_066_DCYL_S2': 185749, '122021_Coralina_2021_Baya_001_DCYL_S24': 73062, '122021_Coralina_2021_Baya_009_DCYL_S25': 41985, '122021_Coralina_2021_Baya_010_DCYL_S26': 34868, '122021_Coralina_2021_Baya_025_MMEA_S22': 72876, '122021_Coralina_2021_Baya_029_MMEA_S23': 40060, '122021_Coralina_2021_Baya_031_MMEA_S45': 84236, '072023_Carolina_2023_Baya_057_SSID_S7': 135591, '072023_Carolina_2023_Baya_059_SSID_S8': 191087, '072023_Carolina_2023_Baya_061_SSID_S5': 393463, '072023_Carolina_2023_Baya_063_SSID_S6': 826442, '122021_Coralina_2021_Baya_019_SSID1_S46': 292470, '122021_Coralina_2021_Baya_021_SSID2_S36': 408795, '122021_Coralina_2021_Baya_027_PSTR4_S34': 438862, '122021_Coralina_2021_Baya_033_PSTR7_S35': 154206, '122021_Coralina_2021_Baya_035_PSTR_S32': 147351, '122021_Coralina_2021_Baya_037_PSTR_S33': 108298, '122021_Coralina_2021_Baya_013_DLAB_S43': 90467, '122021_Coralina_2021_Baya_015_DLAB_S44': 549905}

In [18]:
# Convert main df to raw abundances 
normalized_otus_f=otu_table_f.loc[:,otu_table_f.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus_f.columns = normalized_otus_f.columns.str.replace('_F_filt.bracken_num', '')
normalized_otus_f

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
49546,85828,10467,21432,7583,12184,14772,31365,5852,13507,3315,...,15237,29794,7042,4506,27060,2926,4295,11171,9872,7463
186817,70727,8020,12471,6823,10382,13973,13161,5239,7184,2432,...,6663,26615,5645,4947,25787,2471,4600,10579,9267,6788
31979,36511,3112,5494,2037,3535,4034,3270,1916,2371,918,...,5770,11421,2489,1993,8960,971,2074,4311,3816,2624
543,28875,3537,8342,4084,6086,9514,19052,2258,5152,2406,...,3243,10016,2786,2712,12169,1634,2407,4370,3627,3425
468,26901,1908,3224,1657,2586,3626,4580,1557,2133,980,...,1881,6052,1494,1426,8364,767,1501,2786,2616,1683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675071,0,0,0,0,0,0,0,0,0,0,...,0,13,0,0,0,0,0,0,0,14
11006,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
11974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,10,0,0,0,0,0
2169568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,17,20,0
151341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,14,0,10

In [19]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df_f = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df_f

,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,...,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
Total_reads,139792,301955,48554,72316,137799,50856,92844,1169015,86830,185749,...,393463,826442,292470,408795,438862,154206,147351,108298,90467,549905

In [20]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus_f = pd.concat([normalized_otus_f, sample_counts_df_f],axis=0)
normalized_otus_f

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
49546,85828,10467,21432,7583,12184,14772,31365,5852,13507,3315,...,15237,29794,7042,4506,27060,2926,4295,11171,9872,7463
186817,70727,8020,12471,6823,10382,13973,13161,5239,7184,2432,...,6663,26615,5645,4947,25787,2471,4600,10579,9267,6788
31979,36511,3112,5494,2037,3535,4034,3270,1916,2371,918,...,5770,11421,2489,1993,8960,971,2074,4311,3816,2624
543,28875,3537,8342,4084,6086,9514,19052,2258,5152,2406,...,3243,10016,2786,2712,12169,1634,2407,4370,3627,3425
468,26901,1908,3224,1657,2586,3626,4580,1557,2133,980,...,1881,6052,1494,1426,8364,767,1501,2786,2616,1683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11006,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
11974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,10,0,0,0,0,0
2169568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,17,20,0
151341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,14,0,10
Total_reads,1169015,139792,301955,135591,191087,393463,826442,86830,185749,73062,...,292470,408795,92844,72876,438862,40060,84236,154206,147351,108298

In [21]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu_f = (normalized_otus_f / normalized_otus_f.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu_f.loc['Total_reads',:]=normalized_otus_f.loc['Total_reads',:]
normalized_otu_f["Sum"]=normalized_otu_f.sum(axis=1)
normalized_otu_f.sort_values(by="Sum", ascending=False)

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,Sum
Total_reads,1.169015e+06,139792.000000,301955.000000,135591.000000,191087.000000,393463.000000,826442.000000,86830.000000,185749.000000,73062.000000,...,408795.000000,92844.000000,72876.000000,438862.000000,40060.000000,84236.000000,154206.000000,147351.000000,108298.000000,6.369734e+06
49546,7.341908e+04,74875.529358,70977.463529,55925.540781,63761.532705,37543.555557,37951.846591,67396.061269,72716.407625,45372.423421,...,72882.496117,75847.658438,61831.055492,61659.473821,73040.439341,50987.701220,72442.058026,66996.491371,68911.706587,1.811484e+06
186817,6.050136e+04,57370.951127,41300.856088,50320.448997,54331.273190,35512.869063,15924.892491,60336.289301,38675.847515,33286.797514,...,65105.982216,60800.913360,67882.430430,58758.789779,61682.476286,54608.480935,68603.037495,62890.648859,62678.904504,1.449032e+06
41294,1.200926e+04,6738.583038,7650.146545,8695.267385,8582.478138,19084.386588,20185.324560,8614.534147,8086.180814,27182.393036,...,11661.101530,15628.365861,33097.315989,9087.139010,64802.795806,153580.416924,11471.667769,53871.368365,28366.174814,1.174449e+06
2062,1.905707e+04,28857.159208,23106.091967,39132.390793,33749.025313,49132.955322,65047.516946,24484.625130,28193.960667,52352.796255,...,17725.265720,26829.951316,16644.711565,32212.859623,22840.738892,22436.962819,21834.429270,21750.785539,24312.545015,8.226414e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10477,1.026505e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.026505e+01
39748,9.409631e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.409631e+00
39724,9.409631e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.409631e+00
3424631,8.554210e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.554210e+00
3044467,8.554210e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.554210e+00

In [23]:
# export otu table to csv
normalized_otu_f.to_csv("otu_normtable_family.csv")